### ISSUE TITLE
Release for 15

### ISSUE THREAD

**Issue by rullzer** [rullzer/dropit#16]

**Comment by markymif** [comment]
Hi, any news on this post?
Hangs on large files and Auto Cleanup NextCloud 13.0.2

**Comment by markymif** [comment]
Hi, just upgraded NextCloud to 15 and its the same issue, if not worse.  Its been stuck at this for 10 hours
![image](https://user-images.githubusercontent.com/17123047/51520683-4827db80-1e1c-11e9-9b55-93f1ad56e862.png)

**Comment by Colbix** [comment]
Also experiencing the same issue. The upload indicator stops completely part way through. Checking the DropIt folder shows the file name however 0 KB is actually uploaded. The DropIt text works just fine.

**Comment by nickvergessen** [comment]
This should be closed
