### ISSUE TITLE
Text preview shows only part of it

### ISSUE THREAD

**Issue by tobiasKaminsky** [rullzer/dropit#2]
Currently there is shown only a snippet of the text:
https://nextcloud.kaminsky.me/index.php/s/yWrw0BPrVulQ0qH

Would be great if the complete file can be shown as downloading the file is delaying it for the receiving user.

**Comment by rullzer** [comment]
Ah actually this would be something we'd need to fix in the files_texteditor. To just display more of text files in the editor.

**Comment by tobiasKaminsky** [comment]
I asked over there https://github.com/nextcloud/files_texteditor/issues/72.
Then we would need some kind of option to pass to the editor to say "full/100%".

**Comment by rullzer** [comment]
This is in master of the texteditor.

It won't show full if you drop a 200mb text file. but for the 99% it will show the full text
